name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
      - name: Build Flask app
        run: |
          source env/bin/activate
          flask build
      - name: Build Jekyll site
        uses: helaili/jekyll-action@v2.0.0
        with:
          # Set the path to your Jekyll site folder
          jekyll_src: ./
          jekyll_dest: ./_site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
